### ISSUE TITLE
Support Crowd 2.7.x

### ISSUE THREAD

**Issue by Fjodor42** [dwimberger/crowd-ldap-server#14]
First of all: Brilliant idea!

Next, though, Crowd 2.7.0 has been out for quite some time, and 2.7.1 has been released as well. I don't know how much work it would be to support 2.7 - I don't even know if it should just work anyway - but it would be super if support could be added.

**Comment by SEBiGEM** [comment]
I have successfully tested the current `1.0.4-SNAPSHOT` version (built from the Git repository sources) with Crowd 2.7.1. You can set the version for the `crowd-integration-client-rest` artifact in the pom.xml from `2.3.6` to a higher version (e.g. `2.7.1`) if you want, but it makes the resulting jar file only bigger and doesn’t seem to affect the functionality.

**Comment by dwimberger** [comment]
Recently verified against Crowd 2.8.3 without problems. Locally this is easy to achieve with the Atlassian Plugin SDK.
