### ISSUE TITLE
Group Search Not Returning

### ISSUE THREAD

**Issue by bassrock** [dwimberger/crowd-ldap-server#18]
Hi,

I recently became interested in groups since I use this with grayling and they just enabled group support. However when I use a ldap browser I am not getting any returned groups. I am using Crowd 2.8.1 is it possible something changed in Crowd?

**Comment by dwimberger** [comment]
Group search should work properly:

```
  ldapsearch -WxD "uid=${USER_UID},ou=users,dc=crowd" -H ldap://localhost:10389 -b "dn=${GROUP_ID},ou=groups,dc=crowd"
```

Groups should be shown properly in an LDAP Browser, if the right DN is used.
https://github.com/dwimberger/crowd-ldap-server/wiki/DN's

Verified with Crowd 2.8.3 (latest).

![screen shot 2015-11-14 at 14 08 05](https://cloud.githubusercontent.com/assets/164108/11163690/2d150df6-8ad9-11e5-808c-0c23a08f6741.png)

![screen shot 2015-11-14 at 14 05 33](https://cloud.githubusercontent.com/assets/164108/11163688/085bb6f4-8ad9-11e5-9368-eb4142f27d64.png)

If you need AD type support for groups (memberof) and nested groups, please see:
https://github.com/dwimberger/crowd-ldap-server/wiki/Configuration#user-content-configuring-memberof-ad-emulation
