### ISSUE TITLE
Support nested groups

### ISSUE THREAD

**Issue by adoom42** [dwimberger/crowd-ldap-server#7]
Please add support for nested groups.

Example:
- Add a directory from the Crowd web interface.  Enable the 'Use Nested Groups' option.
- From the Crowd web interface, create a new group within the directory.  You have the ability to add both users and groups as members.  The Nested Members tab shows all users - those directly assigned as well as those who are members of an assigned group.
- Retrieve group information through crowd-ldap-server using a standard LDAP query.  The 'member' attribute contains direct members, not nested ones.

**Comment by dwimberger** [comment]
Added support within the AD emulation. See Configuration for instructions on how to enable this new feature.
